#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# gordon ramsey but in commit hooks
# Check Prettier standards
pnpm run check-format ||
(
    echo '🤢🤮🤢🤮 YOU SURPRISE ME BY HOW BAD YOUR FORMATTING IS - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run pnpm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
pnpm run check-lint ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# # Test server
# cd apps/server && pnpm run test && cd ../.. ||
# (
#     echo '🤡😂❌🤡🧪 Failed Tests 🧪🤡😂❌🤡
#             Are you seriously trying to write that? Fix that shit.'
#     false;
# )


# Check tsconfig standards
pnpm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

pnpm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
